# coding: utf-8

"""
    Streams Api

    API that provides access to Moralis Streams  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_streams
from openapi_streams.model.aptos_coin_withdrawal import AptosCoinWithdrawal
from openapi_streams import configuration


class TestAptosCoinWithdrawal(unittest.TestCase):
    """AptosCoinWithdrawal unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
