# coding: utf-8

# flake8: noqa

"""
    EVM API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.2
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from openapi_evm_api.api_client import ApiClient

# import Configuration
from openapi_evm_api.configuration import Configuration

# import exceptions
from openapi_evm_api.exceptions import OpenApiException
from openapi_evm_api.exceptions import ApiAttributeError
from openapi_evm_api.exceptions import ApiTypeError
from openapi_evm_api.exceptions import ApiValueError
from openapi_evm_api.exceptions import ApiKeyError
from openapi_evm_api.exceptions import ApiException
