# coding: utf-8

"""
    Auth API

    API that provides authentication services for dapps.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_auth
from openapi_auth.model.solana_complete_challenge_response_dto import SolanaCompleteChallengeResponseDto
from openapi_auth import configuration


class TestSolanaCompleteChallengeResponseDto(unittest.TestCase):
    """SolanaCompleteChallengeResponseDto unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
