# coding: utf-8

"""
    EVM API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.2
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_evm_api
from openapi_evm_api.model.internal_transaction import InternalTransaction
from openapi_evm_api import configuration


class TestInternalTransaction(unittest.TestCase):
    """InternalTransaction unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
