# coding: utf-8

"""
    aptos-api

    The aptos-api provider  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_aptos_api
from openapi_aptos_api.model.get_coin_transfers_by_block_heights_response import GetCoinTransfersByBlockHeightsResponse
from openapi_aptos_api import configuration


class TestGetCoinTransfersByBlockHeightsResponse(unittest.TestCase):
    """GetCoinTransfersByBlockHeightsResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
