# coding: utf-8

"""
    Solana API

    Moralis Solana API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from openapi_sol_api.paths.token_network_address_metadata.get import GetTokenMetadata
from openapi_sol_api.paths.token_network_address_price.get import GetTokenPrice


class TokenApi(
    GetTokenMetadata,
    GetTokenPrice,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
